# Generated by Django 4.1.1 on 2022-09-30 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_tast'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tast',
            new_name='Task',
        ),
    ]
